### ISSUE TITLE
Returns undefined in winter

### ISSUE THREAD

**Issue by andrejpavlovic** [LaTableRouge/seasonsCalc#1]
Date `2023-12-22` returns undefined.

https://github.com/LaTableRouge/seasonsCalc/blob/3010e6319505c40a67248d55ab0425ba4545e88f/seasonsCalc.js#L88-L90

I've changed it to
```javascript
  } else {
    return 'winter'
  }
```

**Comment by LaTableRouge** [comment]
Hello @andrejpavlovic thanks a lot I missed that... my apologies.
I've published a new version with the fix in it ;) https://github.com/LaTableRouge/seasonsCalc

**Comment by andrejpavlovic** [comment]
Thank you!
