### ISSUE TITLE
Equinox data needs to be updated

### ISSUE THREAD

**Issue by andrejpavlovic** [LaTableRouge/seasonsCalc#2]
As per:
https://gist.github.com/derickr/f32dd7a05d5c0a099db4e449111f5ccd?permalink_comment_id=4606196#gistcomment-4606196

**Comment by LaTableRouge** [comment]
Hello @andrejpavlovic Thanks for the info.
I've updated the equinox datas in the new release :) https://github.com/LaTableRouge/seasonsCalc

**Comment by andrejpavlovic** [comment]
Awesome!
